require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Layout/LineLength:
  Max: 120

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Rails/I18nLocaleTexts:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5
  Exclude:
    - 'spec/controllers/**/*'

RSpec/IndexedLet:
  Enabled: false

FactoryBot/CreateList:
  Enabled: true

FactoryBot/FactoryClassName:
  Enabled: true

FactoryBot/AssociationStyle:
  EnforcedStyle: implicit 